spring.application.name=smart-task-manager-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/smart-task
spring.datasource.username=postgres
spring.datasource.password=Monika123@
spring.jpa.hibernate.ddl-auto=update

jwt.secret=byJnYS4T7JzzzxzJ6GVST8Zu4Lb93AVL
jwt.expiration=86400000
