spring.application.name=smart-task-manager-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:smart-task}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:Monika123@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:byJnYS4T7JzzzxzJ6GVST8Zu4Lb93AVL}
jwt.expiration=86400000
#spring.application.name=smart-task-manager-backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/smart-task
#spring.datasource.username=postgres
#spring.datasource.password=Monika123@
#spring.jpa.hibernate.ddl-auto=update
#
#jwt.secret=byJnYS4T7JzzzxzJ6GVST8Zu4Lb93AVL
#jwt.expiration=86400000
